/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cn_itcast_TestNative */

#ifndef _Included_cn_itcast_TestNative
#define _Included_cn_itcast_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_itcast_TestNative
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_itcast_TestNative_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
